#== 外周部 ==!
# 青目印を超えるとLAP
#- LineTracer 2000 55 80 100 LEFT_EDGE 0.6 0.01 0.017 BLUE
# 青目印を超えるとLAP
#- LineTracer 2000 55 40 80 LEFT_EDGE 0.3 0.01 0.01 BLACK

#== 外周部 (PWM80_success) ==!
# ボトルまで行く
#- ScenarioTracer 50 50 50
# アームを上げる（このあとに色判定を行う？）
#- ArmTracer -30 -120
# アームを下げてボトルをキープ
#- ArmTracer 30 120
# 青目印を超えるとLAP
#- LineTracer 2000 55 80 100 LEFT_EDGE 0.6 0.01 0.017 BLUE

#== 外周部 (PWM60_success) ==!
# ボトルまで行く
#- ScenarioTracer 50 50 50
# 青目印を超えるとLAP
#- LineTracer 2000 55 60 80 LEFT_EDGE 0.4 0 0.012 BLUE
# アームを上げる（このあとに色判定を行う？）
#- ArmTracer -30 -120
# アームを下げてボトルをキープ
#- ArmTracer 30 120

#== ボトルデリバリー ==!
# 青目印を超えるとLAP
#- LineTracer 2000 55 40 80 LEFT_EDGE 0.3 0.01 0.01 BLUE
# 青目印を超えるとLAP
#-- LineTracer 2000 55 60 80 LEFT_EDGE 0.4 0 0.012 BLUE
# 青目印を超えるとLAP
#- LineTracer 2000 55 80 100 LEFT_EDGE 0.6 0.01 0.017 BLACK
# 赤色で止まる
#- LineTracer 2000 55 60 80 LEFT_EDGE 0.4 0 0.017 BLUE
# 赤色で止まる
#- LineTracer 2000 55 60 80 LEFT_EDGE 0.4 0 0.017 BLACK
# 赤色で止まる
#- LineTracer 2000 55 60 80 LEFT_EDGE 0.4 0 0.017 BLUE
# 赤色で止まる
#- LineTracer 2000 55 60 80 LEFT_EDGE 0.4 0 0.017 BLACK
# 赤色で止まる
#- LineTracer 2000 55 60 80 LEFT_EDGE 0.4 0 0.017 BLUE

#== ETラリー ==!
#- ScenarioTracer 30 50 50
#- RotateTracer TURN_RIGHT 90 35

#== ET相撲 ==
# 前方の対象までの超音波距離を、100ms間隔で記録する。ロボットは走行・旋回しない。
RotateTracer TURN_LEFT 45 30
UltrasonicAlignTracer 60 500 150
# 前方の対象までの超音波距離を、100ms間隔で記録する。ロボットは走行・旋回しない。
RotateTracer TURN_LEFT 45 50
ScenarioTracer 100 40 40 BLACK
ScenarioTracer 50 40 40
RotateTracer TURN_LEFT 90 50
# 青目印を超えるとGoal
LineTracer 2000 55 80 100 LEFT_EDGE 0.6 0.01 0.017 BLUE
ScenarioTracer 90 40 40

#== ゴール ==!
#- ScenarioTracer 1000 50 50 BLACK
#- ScenarioTracer 50 50 50
#- LineTracer 500 35 40 80 RIGHT_EDGE 0.45 0.0 0.05 BLUE

#end
#end までしか読み取らないのでこの下は使われない
