#== 外周部 ==
# 青目印を超えるとLAP
LineTracer 2000 35 40 80 LEFT_EDGE 0.2 0.0 0.05 BLUE
# ボトルまで行く
ScenarioTracer 50 50 50
# アームを上げる（このあとに色判定を行う？）
ArmTracer -30 -120
# アームを下げてボトルをキープ
ArmTracer 30 120

#== ボトルデリバリー ==!
# コース中盤の青目印まで行く
#- LineTracer 500 35 40 80 LEFT_EDGE 0.45 0.0 0.05 BLUE
# 青ラインを超えるまで前進（ライントレース外れないようにしたい…）
#- ScenarioTracer 50 50 50
# ボトルデリバリーする先の青目印まで行く
#- LineTracer 500 35 40 80 LEFT_EDGE 0.45 0.0 0.05 BLUE

#== ETラリー ==!
#- ScenarioTracer 30 50 50

#== ET相撲 ==
UltrasonicAlignTracer 90 25 3 3 400 1.56 15
ScenarioTracer 30 50 50

#== ゴール ==!
#- ScenarioTracer 1000 50 50 BLACK
#- ScenarioTracer 50 50 50
#- LineTracer 500 35 40 80 RIGHT_EDGE 0.45 0.0 0.05 BLUE

#end
#end までしか読み取らないのでこの下は使われない
