ScenarioTracer 100 40 40
LineTracer 6000 40 50 80 RIGHT_EDGE 0.7 0 0.08 BLUE
ScenarioTracer 200 67 70
ScenarioTracer 20 70 67 BLACK
LineTracer 4000 80 50 80 LEFT_EDGE 0.4 0 0.1 BLUE
ScenarioTracer 380 74 68
ScenarioTracer 200 40 24 BLACK
LineTracer 4000 75 50 80 RIGHT_EDGE 0.4 0 0.1 BLUE
ScenarioTracer 250 70 44
ScenarioTracer 60 50 75 BLACK
LineTracer 4000 70 40 80 LEFT_EDGE 0.4 0 0.1 BLUE
ScenarioTracer 200 68 80
LineTracer 6000 70 50 80 RIGHT_EDGE 0.4 0 0.1 BLUE
#デブリリムーバル
# Rコースで読む
#
# ボトルがあったらどかす
DifficultScenarioTracer TURN_RIGHT
#
ScenarioTracer 40 50 50
# 2個目の青まで前進
LineTracer 330 35 50 80 RIGHT_EDGE 0.4 0.0 0.2 BLUE
# ボトルがあったらどかす
DifficultScenarioTracer TURN_RIGHT
#
ScenarioTracer 25 50 40
# 左に回る
RotateTracer TURN_LEFT 95 85
ScenarioTracer 50 40 40
#
# 2個目の青を抜けるまで前進
ScenarioTracer 20 40 45
# 3個目の青まで前進
LineTracer 330 35 40 80 LEFT_EDGE 0.4 0.0 0.2 BLUE
# ボトルがあったらどかす
DifficultScenarioTracer TURN_LEFT
#
# 1個目の緑まで前進
LineTracer 330 35 40 80 LEFT_EDGE 0.4 0.0 0.2 GREEN
# ボトルがあったらどかす
DifficultScenarioTracer TURN_LEFT
#
# 右に回る
RotateTracer TURN_RIGHT 80 85
# 1個目の黄色まで前進
LineTracer 330 35 40 80 RIGHT_EDGE 0.4 0.0 0.2 YELLOW
# ボトルがあったらどかす
DifficultScenarioTracer TURN_LEFT
#
# 右に回る
RotateTracer TURN_RIGHT 90 80
# 1個目の赤まで前進
LineTracer 330 35 40 80 RIGHT_EDGE 0.4 0.0 0.2 RED
# ボトルがあったらどかす
DifficultScenarioTracer TURN_RIGHT
#
ScenarioTracer 20 -40 -40
# 1個目の赤を抜けるまで前進
LineTracer 40 35 40 80 LEFT_EDGE 0.45 0.0 0.2
# 2個目の赤まで前進
LineTracer 330 35 40 80 LEFT_EDGE 0.45 0.0 0.2 RED
# ボトルがあったらどかす
DifficultScenarioTracer TURN_RIGHT
#
# 左に回る
RotateTracer TURN_LEFT 90 85
# 2個目の赤を抜けるまで前進
ScenarioTracer 40 40 40
# 3個目の赤まで前進
LineTracer 330 35 40 80 LEFT_EDGE 0.45 0.0 0.2 RED
# ボトルがあったらどかす
DifficultScenarioTracer TURN_RIGHT
#
# 左に回る
RotateTracer TURN_LEFT 100 90
ScenarioTracer 20 40 50
# 4個目の赤まで前進
LineTracer 330 35 40 80 LEFT_EDGE 0.35 0.0 0.2 RED
# ボトルがあったらどかす
DifficultScenarioTracer TURN_LEFT
# 4個目の赤を抜けるまで前進
ScenarioTracer 40 40 50
# 2個目の黄色まで前進
LineTracer 330 35 50 80 RIGHT_EDGE 0.4 0.0 0.2 YELLOW
# ボトルがあったらどかす
DifficultScenarioTracer TURN_LEFT
#
# 2つめの黄色を抜けるまで前進
ScenarioTracer 100 50 50
# 3個目の黄色で停止（シナリオ3へ渡しシナリオ2ゴール）
LineTracer 330 35 50 80 LEFT_EDGE 0.4 0.0 0.2 YELLOW
#
# スマートキャリー
# ディセーブルゾーン方向へ直進（低速）
ScenarioTracer 220  50  50
# 右方向に旋回　左モーターのみ距離30旋回
ScenarioTracer 40  80  -50
# ディセーブルゾーンの上に直進（低速）
ScenarioTracer 150  50  50
# 左方向に旋回　右モーターのみ距離 70旋回
ScenarioTracer 60  -50  80
# ボトルをキャリーしながらターゲットサークル方向へ直進（低速）
ScenarioTracer 1000 50 50
# 後ろ方向へ直進（低速）
ScenarioTracer 200 -50 -50
# 右方向に旋回　左モーターのみ距離 110旋回
ScenarioTracer 70 50 -80
# ゴールラインに向かって直進（低速）
ScenarioTracer 800 50 50 BLACK
# 右方向に旋回　左モーターのみ距離 110旋回
ScenarioTracer 25  40 -60
# 右方向に旋回　左モーターのみ距離 110旋回
ScenarioTracer 50  50 50
# 3個目の青まで前進
LineTracer 700 35 40 RIGHT_EDGE 0.4 0.0 0.2 BLUE
#
#end
#end までしか読み取らないのでこの下は使われない
